# This workflow builds & runs test cases in iceoryx

name: Build & Test

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master, u-workflow-for-mac-enable-tests ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # # This job builds & runs iceoryx tests in ubuntu-18.04
  # build-test-ubuntu:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-18.04
      
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Install iceoryx dependencies
  #       # Softwares installed in ubuntu-18.04 instance 
  #       # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
  #       run: sudo apt-get update && sudo apt-get install -y libacl1-dev libncurses5-dev
      
  #     - name : Checkout
  #       uses: actions/checkout@v2
 
  #     - name: Build with GNU
  #       run: ./tools/iceoryx_build_test.sh
      
  #     - name: Build Tests
  #       run: "./tools/iceoryx_build_test.sh build-test"  

  #     - name: Execute Tests
  #       run: "./tools/iceoryx_build_test.sh test"  
        
  #     - name : Build with clang
  #       run: |
  #         export CC=/usr/bin/clang
  #         export CXX=/usr/bin/clang++
  #         ./tools/iceoryx_build_test.sh clean

  # This job builds & runs iceoryx tests in macos-10.15
  build-test-mac:
    runs-on: macos-10.15
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install iceoryx dependencies
        # Softwares installed in macos-10.15 instance
        # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
        # May be this contains some dependencies required by iceoryx introspection
        run:  brew install gsl
      
      - name : Checkout
        uses: actions/checkout@v2
 
      - name: Build with GNU
        # iceoryx introspection build fails in mac , hence disable for now
        run: ./tools/iceoryx_build_test.sh
      
      - name: Build Tests
        run: ./tools/iceoryx_build_test.sh skip-introspection build-test

      - name: Run Tests
        run: |
          cd build
          ../tools/run_mac_tests.sh        

      
