name: Build with colcon

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master,u_colcon_build ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.0.15
        
      - name: Install iceoryx dependencies
        # Softwares installed in ubuntu-18.04 instance 
        # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
        run: sudo apt-get update && sudo apt-get install -y libacl1-dev libncurses5-dev
      
#       - name: Build with colcon
#         uses: ros-tooling/action-ros-ci@master
#         with:
#           package-name: iceoryx
#           vcs-repo-file-url: |
#             https://gist.githubusercontent.com/Karsten1987/1723f219bb5aa5b81355c7eb1477f867/raw/9dc4d877f6fd0f862070516febdbddea28723b5c/iceoryx.repos
            
      - name : Checkout
        uses: actions/checkout@v2
        with:
           # Relative path under $GITHUB_WORKSPACE to place the repository
            path: 'iceoryx_ws/src/'
  
      - name : Build with colcon
        run: |
          cd $GITHUB_WORKSPACE/iceoryx_ws/
          colcon build  
          colcon test        
            
